- name: varspreferences
  hosts: local
  connection: local
  vars:
    greeting: "hello from play"
  vars_files:
    - course.yaml
  vars_prompt:
  - name: greeting
    prompt: please enter 
    private: false

  tasks:
  - name: print greeting
    vars:
      greeting "hello task"
    ansible.builtin.debug:
     msg: "{{greeting}}"