- name: data types
  hosts: localhost
  connection: local
  vars:
    DURATION: 120 # number
    COURSE: "devsecops woth aws"
    IS_LIVE: true # boolean
    TOOLS: # list []
    - linux
    - shell
    - ansible
    CONCEPTS: #map or dictonary or objects
      CI: jenkins
      SCRIPTINGS: "shell , ansible , teraforms , python"
    TASKS:
    - name: print information
      ansible.builtin.debug:
        msg: "course is : {{COURSE}} , Duration : {{DURATION}} , is alive: {{IS_LIVE}}, Tools are : {{TOOLS}} , concepts are {{CONCEPTS}}"