- name: when condition
  hosts: local
  connection: local
  vars:
    number: 70 
  tasks:
  - name: print number is greater than 100
    ansible.builtin.debug:
     msg: "Given number {{number}} is greater thaan 100"
    when: number > 100

  - name: print number is less than 100
    ansible.builtin.debug:
     msg: "Given number {{number}} is greater thaan 100"
    when: number < 100