- name: install packages using loops 
  hosts: display
  become: yes
  tasks:
  - name: install
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed

    loop:
    - mysql
    - nginx
    - zip