- name: install packages using loops 
  hosts: local
  connection: local
  tasks:
  - name: install
    ansible.builtin.package:
      name: "{{ item }}"
      state: install

    loop:
    - mysql
    - nginx
    - zip